services:
  user_service:
    build:
      context: .                          # ✅ Set build context to project root
      dockerfile: user/Dockerfile 
    # container_name: user_service ❌ Remove this when using replicas
    # ports:
    #   - "8001:8001"
    volumes:
      - ./user:/code
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    networks:
      - mynetwork

  user_education_service:
    build: ./user_education
    # container_name: user_education_service
    # ports:
    #   - "8000:8000"
    volumes:
      - ./user_education:/code
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    networks:
      - mynetwork

  socket_service:
    build:
      context: ./socket_service
      dockerfile: Dockerfile
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx_conatiner
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - user_education_service
      - socket_service
    networks:
      - mynetwork

# ✅ Moved to root level
networks:
  mynetwork:
    driver: bridge   # Use "overlay" if you're using Docker Swarm
