services:
  client_service:
    build: ./client_group_service
    container_name: client_service
    ports:
      - "8001:8001"
    volumes:
      - ./client_group_service:/code
    env_file:
      - .env

  user_education_service:
    build: ./user_education
    container_name: user_education_service
    ports:
      - "8000:8000"
    volumes:
      - ./user_education:/code
    env_file:
      - .env

